# Teamfight Tactics Monetization Analysis
## Data source
The data was created using chatgpt-4o (check link:https://chatgpt.com/c/6718fc2e-8e1c-800b-aeb7-33697fa34480) JC

In [5]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../2-prepared Data/Teamfight_Tactics_Monetization_Dataset.csv")

In [4]:
display(df)

,player_id,region,total_playtime_hours,days_active,spending_category,total_spent,battle_pass_purchases,skins_purchased,loot_boxes_purchased,days_since_last_purchase,daily_sessions,sessions_per_week,churn_status,d1_retention,d7_retention,d30_retention,arpu,arppu
0,1,EU,25,62,Free,0,0,1,2,11,0,11,No,1,1,0,0.000000,0.000000
1,2,LATAM,43,262,Free,200,0,1,2,52,1,23,Yes,1,0,1,0.763359,0.763359
2,3,APAC,119,218,Free,0,1,4,2,38,1,41,No,1,1,0,0.000000,0.000000
3,4,EU,41,232,Dolphin,0,0,1,5,45,0,17,No,1,1,1,0.000000,0.000000
4,5,NaN,155,336,Small Spender,50,0,0,4,1,0,37,No,1,0,0,0.148810,0.148810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,LATAM,98,340,Dolphin,0,0,2,5,43,2,27,Yes,1,0,0,0.000000,0.000000
9996,9997,LATAM,139,8,Free,0,0,1,3,28,4,1,No,1,0,0,0.000000,0.000000
9997,9998,LATAM,149,270,Small Spender,10,1,4,6,4,3,26,No,1,0,0,0.037037,0.037037
9998,9999,EU,65,318,Free,50,0,3,1,49,1,12,No,1,1,0,0.157233,0.157233
9999,10000,NaN,84,212,Free,100,0,1,2,35,4,19,Yes,1,0,0,0.471698,0.471698